---
title: "Borrador métricas"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(jsonlite)
library(tidyverse)
```


```{r load_data}


df <- fromJSON("epa_glm/experimental/modelDetails.json")
metricas_training <- df$output$training_metrics$thresholds_and_metric_scores$data %>% t() %>% as.data.frame()

colnames(metricas_training) <- df$output$training_metrics$thresholds_and_metric_scores$columns$name
```





Column {data-width=50}
-----------------------------------------------------------------------


### **AUC**

```{r}
gauge(round(df$output$training_metrics$AUC,2), min = 0.5, max=1)
```

### **F1 score**

```{r}
metricas_training[which.max(metricas_training$f1), c("f1","threshold")]
```


### Info

```{r}
df$algo_full_name
```


Column {data-width=350}
-----------------------------------------------------------------------

### ROC

```{r}
plotly::ggplotly(ggplot(metricas_training, aes(x = fpr, y = tpr)) +
  geom_line() + geom_abline(intercept = 0, slope = 1))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Gain Lift

```{r}
gain_lift_data <- as.data.frame(t(df$output$training_metrics$gains_lift_table$data))
colnames(gain_lift_data) <- df$output$training_metrics$gains_lift_table$columns$name

gain_lift_data[,] <- sapply(gain_lift_data[,], function(x) as.numeric(as.character(x)))

DT::datatable(round(gain_lift_data,2), rownames = FALSE)
```



